<?php
/*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 * Developer Notes:
 *        Discussion about TOS for this site here: 
 *        https://github.com/POSSA/Caller-ID-Superfecta/issues/182#issuecomment-38616185
 * 
 *
 * Version History
 *        2014-03-25   Initial release by Håkan
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***/
 
class SE_eniro_HE extends superfecta_base {
        public $description = "http://www.eniro.se - Only corporate info avail at the moment...";
        public $version_requirement = "2.11";

    public $source_param = array(
             'API_Profile' => array (
               'description' => 'Name of your profile registered to ENIRO.',
               'type' => 'text',
               'default' => 'profilename'
             ),
             'API_Key' => ARRAY (
               'description' => 'API Key is REQUIRED. Login to api.eniro.se and read your Key from profile settings.',
               'type' => 'text',
		'default' => '00112233445566778899'
             )
    );


	function get_caller_id($thenumber, $run_param=array()) {
		
                $this->DebugPrint("Searching eniro.se... ");
                $number_error = false;

		//check for the correct digits for Sweden in international format.
		// international dialing prefix + country code + number

		if (strlen($thenumber) > 8) {
			if (substr($thenumber,0,2) == '46')
			{
				$thenumber = '0'.substr($thenumber, 2);
			}
			else
			{
				if (substr($thenumber,0,4) == '0046')
				{
					$thenumber = '0'.substr($thenumber, 4);
				}
				else
				{
					if (substr($thenumber,0,5) == '01146')
					{
						$thenumber = '0'.substr($thenumber,5);
					}
					else
					{
						$number_error = true;
					}
				}
			}
		}

		// number
		if(strlen($thenumber) < 11)
		{
			if (substr($thenumber,0,1) == '0')
			{
				$number_error = false;
			}
			else
			{
				$number_error = true;
			}
		}

		if(!$number_error)
		{
			$this->DebugPrint("Numret ar svenskt, slar nu upp numret.");
                        $this->DebugPrint("Search for an coorporation in eniro.se... ");

                        $url="http://api.eniro.com/cs/search/basic?profile=".$run_param['API_Profile']."&key=".$run_param['API_Key']."&version=1.1.3&country=se&search_word=$thenumber";
                        $value = $this->get_url_contents($url);

			$this->DebugPrint("URL=".$url."\n");
			$this->DebugPrint("RETURN=".$value."\n");

                        $notfound = strpos($value, "\"totalHits\" : 0"); //No hit.
                        $notfound = ($notfound < 1) ? strpos($value, "\"totalHits\" : 0") : $notfound;
                        if($notfound)
                        {
                                $value = "";
                                $this->DebugPrint("eniro.se reports number not found!<br>\n");
                        }
                        else
                        {
                                $start = strpos($value, "\"companyName\" : \"");// STARTPOS is position for the first ["] in "companyName" : "

                                $value = substr($value,$start+17);		// Skip text "companyName" : "
				$this->DebugPrint("NEWVAULE=".$value."\n");

                                $end = strpos($value, "\"");			// Look for next ["] indication the end of the name of the company
                                $value = substr($value,0,$end);			// Save result in $value from startpost 0 to endpos $end
                        }
                        if (strlen($value) > 1)
                        {
                                $caller_id = strip_tags($value);
                                return($caller_id);
                        }
                        else
                        {
                                $this->DebugPrint("eniro.se returns no data!<br>\n");
                        }
		}
		else 
		{
			$this->DebugPrint("Skipping Source - Non Swedish number: ".$thenumber."<br>\n");
		}
   	}
}
